### ISSUE TITLE
Upon unselecting 'multiselect', an error occurs.

### ISSUE THREAD

**Issue by psiotwo** [lecbyjak/IntelligentTreeSelectComponent#1]
Upon running the project according to the instructions in README.md, clicking on Filter and deselecting 'Multiselect', the following error occurs:
![image](https://user-images.githubusercontent.com/1140626/40905635-da0fb058-67de-11e8-97e1-8a1c8e7bae7f.png)

**Comment by lecbyjak** [comment]
fixed with commit 4c12e90f85f347519368883bea4ac1f4e84633d0
